name: kazoo-application-ecallmgr-extension
custom_files: null
exposure: private
base_branch: origin/5.5
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-ecallmgr-extension
    summary: 'Kazoo paid application ecallmgr-extension.'
    description: |
      A proprietary Kazoo application from 2600Hz.
    app_name: ecallmgr_extension
    license: proprietary
    group: Productivity/Telephony
    url: 'http://www.2600hz.com/'
    vendor: 2600Hz
  rockylinux8:
    name: kazoo-application-ecallmgr-extension
    summary: 'Kazoo paid application ecallmgr-extension.'
    description: |
      A proprietary Kazoo application from 2600Hz.
    app_name: ecallmgr_extension
    license: proprietary
    group: Productivity/Telephony
    url: 'http://www.2600hz.com/'
    vendor: 2600Hz
    dist: .el8
  rockylinux9:
    name: kazoo-application-ecallmgr-extension
    summary: 'Kazoo paid application ecallmgr-extension.'
    description: |
      A proprietary Kazoo application from 2600Hz.
    app_name: ecallmgr_extension
    license: proprietary
    group: Productivity/Telephony
    url: 'http://www.2600hz.com/'
    vendor: 2600Hz
    dist: .el9
metapackage:
  -
    name: meta-kazoo-applications
    type: related
    branch: '5.5'
    package: kazoo-application-ecallmgr-extension
dependencies: null
