---
name: kazoo-application-ecallmgr-extension
base_branch: origin/master
metapackage:
  - name: meta-kazoo-applications
    type: related
    branch: master
    package: kazoo-application-ecallmgr-extension
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-ecallmgr-extension
    summary: Kazoo paid application ecallmgr-extension.
    description: |
        A proprietary Kazoo application from 2600Hz.
    app_name: ecallmgr_extension
    license: proprietary
    group: Productivity/Telephony
    url: http://www.2600hz.com/
    vendor: 2600Hz
  app_exchange:
    type: kazoo-application
    core_app:
      name: kazoo_core
    name: ecallmgr_extension
    dependencies:
      - name: ecallmgr
